export type Level = "Einsteiger" | "Fortgeschritten" | "Profi";

export interface Course {
  title: string;
  level: Level;
  price: string;
  priceNum: number;
  status: string;
  modules: string;
  category: string;
}

export const courses: Course[] = [
  { title: "ChatGPT Meisterkurs für Einsteiger", level: "Einsteiger", price: "29,00 €", priceNum: 29, status: "Publiziert", modules: "5 Module · 13 Lektionen", category: "KI-Grundlagen" },
  { title: "Google Gemini Meisterkurs", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 8 Lektionen", category: "KI-Grundlagen" },
  { title: "Claude von Anthropic Meisterkurs", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 13 Lektionen", category: "KI-Grundlagen" },
  { title: "Microsoft Copilot im Berufsalltag", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "KI-Grundlagen" },
  { title: "KI-Tools im Büroalltag", level: "Einsteiger", price: "24,00 €", priceNum: 24, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "KI-Grundlagen" },
  { title: "Datenanalyse mit KI für Einsteiger", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "KI-Grundlagen" },
  { title: "DeepSeek & Open-Source KI verstehen", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "KI-Grundlagen" },
  { title: "ChatGPT Power-User: Custom GPTs, API & Computer Use", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "7 Module · 18 Lektionen", category: "KI-Grundlagen" },
  { title: "Advanced Prompt Engineering: Techniken für Profis", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "7 Module · 16 Lektionen", category: "KI-Grundlagen" },
  { title: "KI-Masterclass: Strategie, Implementierung & Skalierung", level: "Profi", price: "99,00 €", priceNum: 99, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "KI-Strategie" },
  { title: "KI-Strategie für Führungskräfte", level: "Fortgeschritten", price: "69,00 €", priceNum: 69, status: "Publiziert", modules: "5 Module · 7 Lektionen", category: "KI-Strategie" },
  { title: "KI-Change-Management: Teams erfolgreich transformieren", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "KI-Strategie" },
  { title: "KI-ROI messen: Business Cases & Kennzahlen", level: "Fortgeschritten", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "KI-Strategie" },
  { title: "KI-Kompetenz für Teams – EU AI Act Pflichtschulung", level: "Einsteiger", price: "69,00 €", priceNum: 69, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "KI-Strategie" },
  { title: "KI-Governance & Audit: ISO 42001 verstehen", level: "Fortgeschritten", price: "69,00 €", priceNum: 69, status: "Publiziert", modules: "7 Module · 13 Lektionen", category: "KI-Strategie" },
  { title: "KI & Recht: DSGVO und EU AI Act verstehen", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "KI-Strategie" },
  { title: "KI für Datenschutzbeauftragte", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "6 Module · 11 Lektionen", category: "KI-Strategie" },
  { title: "KI-Sicherheit: Prompt Injection, Jailbreaking & Schutz", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 8 Lektionen", category: "KI-Strategie" },
  { title: "KI-Agenten & Workflow-Automatisierung", level: "Fortgeschritten", price: "69,00 €", priceNum: 69, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Automatisierung" },
  { title: "n8n – KI-Automatisierung selbst hosten", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "7 Module · 18 Lektionen", category: "Automatisierung" },
  { title: "No-Code Automatisierung mit Make und Zapier", level: "Einsteiger", price: "44,00 €", priceNum: 44, status: "Publiziert", modules: "5 Module · 13 Lektionen", category: "Automatisierung" },
  { title: "KI-Voice-Agenten: Telefonbots & Sprachassistenten bauen", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "6 Module · 17 Lektionen", category: "Automatisierung" },
  { title: "Computer Use & Browser-Agenten: KI die Ihren PC bedient", level: "Fortgeschritten", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 17 Lektionen", category: "Automatisierung" },
  { title: "RAG für Unternehmen: Firmen-Wissen mit KI durchsuchbar machen", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "7 Module · 21 Lektionen", category: "Automatisierung" },
  { title: "E-Mail-Marketing mit KI automatisieren", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Automatisierung" },
  { title: "WhatsApp Business & KI-Chatbots", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "4 Module · 8 Lektionen", category: "Automatisierung" },
  { title: "KI im Kundenservice: Chatbots & Support automatisieren", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "5 Module · 9 Lektionen", category: "Automatisierung" },
  { title: "HubSpot AI: Marketing & Sales automatisieren", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "6 Module · 13 Lektionen", category: "Marketing & Sales" },
  { title: "KI-Content-Erstellung: Texte, Video & Social Media", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Marketing & Sales" },
  { title: "KI-Texte die verkaufen: Copywriting mit KI", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 12 Lektionen", category: "Marketing & Sales" },
  { title: "LinkedIn-Erfolg mit KI: Personal Branding & Reichweite", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Marketing & Sales" },
  { title: "KI für Social Media: TikTok, Reels & Shorts", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Marketing & Sales" },
  { title: "YouTube mit KI: Skripte, Thumbnails & SEO", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Marketing & Sales" },
  { title: "SEO Grundlagen: Von Null auf Seite 1", level: "Einsteiger", price: "24,00 €", priceNum: 24, status: "Publiziert", modules: "5 Module · 11 Lektionen", category: "Marketing & Sales" },
  { title: "KI für Vertrieb & Sales", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Marketing & Sales" },
  { title: "KI-Customer-Journey: Analyse & Personalisierung", level: "Fortgeschritten", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Marketing & Sales" },
  { title: "Prompting für Marketing-Profis", level: "Fortgeschritten", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Marketing & Sales" },
  { title: "KI-Bilder erstellen für Business & Marketing", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Marketing & Sales" },
  { title: "Midjourney Meisterkurs (Aktualisiert für V8)", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "7 Module · 14 Lektionen", category: "Marketing & Sales" },
  { title: "Canva AI & Design für Nicht-Designer", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 6 Lektionen", category: "Marketing & Sales" },
  { title: "KI für Projektmanagement", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Business & Organisation" },
  { title: "KI für HR & Recruiting", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Business & Organisation" },
  { title: "KI für Finanzen & Buchhaltung", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Business & Organisation" },
  { title: "KI für Startups & Gründer", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Business & Organisation" },
  { title: "Notion AI: Projekte & Wissen mit KI organisieren", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Business & Organisation" },
  { title: "KI-Meeting-Assistent: Transkription, Protokolle & Follow-ups", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "4 Module · 8 Lektionen", category: "Business & Organisation" },
  { title: "Google Workspace AI: Docs, Sheets, Slides & Gmail", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 13 Lektionen", category: "Business & Organisation" },
  { title: "Slack AI, Zoom AI & Teams Copilot: Collaboration-KI meistern", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Business & Organisation" },
  { title: "Excel mit KI: Datenanalyse automatisieren", level: "Fortgeschritten", price: "34,00 €", priceNum: 34, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Business & Organisation" },
  { title: "Power BI & Datenvisualisierung mit KI", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Business & Organisation" },
  { title: "KI für Einkauf & Beschaffung", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Business & Organisation" },
  { title: "KI für Qualitätsmanagement & ISO-Audits", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Business & Organisation" },
  { title: "KI für Coaches, Trainer & Berater", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 14 Lektionen", category: "Business & Organisation" },
  { title: "KI für Bewerbung & Karriere", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Business & Organisation" },
  { title: "GitHub Copilot & KI-Coding für Entwickler", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Technik & Entwicklung" },
  { title: "Vibe Coding – Apps bauen ohne Programmieren", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "7 Module · 14 Lektionen", category: "Technik & Entwicklung" },
  { title: "KI-Sprachmodelle anpassen: Fine-Tuning ohne Code", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "7 Module · 12 Lektionen", category: "Technik & Entwicklung" },
  { title: "Small Language Models & lokale KI im Unternehmen", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 14 Lektionen", category: "Technik & Entwicklung" },
  { title: "Multimodale KI: Text + Bild + Audio + Video kombinieren", level: "Fortgeschritten", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Technik & Entwicklung" },
  { title: "Salesforce AI & CRM mit Einstein", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "7 Module · 10 Lektionen", category: "Technik & Entwicklung" },
  { title: "SAP & KI: ERP-Prozesse automatisieren", level: "Fortgeschritten", price: "69,00 €", priceNum: 69, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Technik & Entwicklung" },
  { title: "WordPress & KI: Websites bauen & optimieren", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 10 Lektionen", category: "Technik & Entwicklung" },
  { title: "OpenClaw – Dein autonomer KI-Assistent", level: "Fortgeschritten", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "7 Module · 14 Lektionen", category: "Technik & Entwicklung" },
  { title: "Cybersecurity-Basics im KI-Zeitalter", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Technik & Entwicklung" },
  { title: "Figma AI & UX-Design mit KI", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "9 Module · 20 Lektionen", category: "Technik & Entwicklung" },
  { title: "KI für Gesundheitswesen & Praxen", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "6 Module · 14 Lektionen", category: "Branchen" },
  { title: "KI für Juristen & Rechtsanwälte", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "6 Module · 13 Lektionen", category: "Branchen" },
  { title: "KI für Banken & Finanzdienstleister", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 15 Lektionen", category: "Branchen" },
  { title: "KI für Versicherungen & Finanzberatung", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Branchen" },
  { title: "KI für Steuerberater & Steuerkanzleien", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Branchen" },
  { title: "KI für Immobilien", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "6 Module · 13 Lektionen", category: "Branchen" },
  { title: "KI für Logistik & Supply Chain", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Branchen" },
  { title: "KI für E-Commerce & Online-Shops", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "6 Module · 14 Lektionen", category: "Branchen" },
  { title: "KI für Einzelhandel & Retail", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "5 Module · 14 Lektionen", category: "Branchen" },
  { title: "KI für Öffentliche Verwaltung & Behörden", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 13 Lektionen", category: "Branchen" },
  { title: "KI für Lehrer & Dozenten", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 15 Lektionen", category: "Branchen" },
  { title: "KI für Personaldienstleister & Zeitarbeit", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "5 Module · 11 Lektionen", category: "Branchen" },
  { title: "KI für Architekten & Ingenieure", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Branchen" },
  { title: "KI für Handwerk & Baubranche", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Branchen" },
  { title: "KI für Gastronomie & Hotellerie", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Branchen" },
  { title: "KI für Tourismus & Reisebüros", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 11 Lektionen", category: "Branchen" },
  { title: "KI für Pharma & Life Sciences", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "5 Module · 11 Lektionen", category: "Branchen" },
  { title: "KI für Landwirtschaft & Agrar", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 13 Lektionen", category: "Branchen" },
  { title: "KI für Wissenschaft & Forschung", level: "Fortgeschritten", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "7 Module · 12 Lektionen", category: "Branchen" },
  { title: "KI für Journalisten & Medien", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "5 Module · 11 Lektionen", category: "Branchen" },
  { title: "KI für Vereine, Verbände & Non-Profits", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Branchen" },
  { title: "KI für Nachhaltigkeit & ESG-Reporting", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Branchen" },
  { title: "KI für Eventmanagement & Messen", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Branchen" },
  { title: "KI-Videos erstellen mit Sora, Runway & Kling", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "6 Module · 13 Lektionen", category: "Kreativ & Medien" },
  { title: "KI-Podcasts & Audio erstellen", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Kreativ & Medien" },
  { title: "KI-Fotografie & Bildbearbeitung", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 10 Lektionen", category: "Kreativ & Medien" },
  { title: "KI-Präsentationen erstellen mit Gamma & Co.", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 12 Lektionen", category: "Kreativ & Medien" },
  { title: "Online-Kurse erstellen mit KI", level: "Einsteiger", price: "59,00 €", priceNum: 59, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Kreativ & Medien" },
  { title: "KI-Bücher schreiben & als eBook veröffentlichen", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "6 Module · 12 Lektionen", category: "Kreativ & Medien" },
  { title: "KI-Texte optimieren: Lektorat, Stil & Tone of Voice", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "3 Module · 6 Lektionen", category: "Kreativ & Medien" },
  { title: "KI für Übersetzen & Lokalisierung", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 12 Lektionen", category: "Kreativ & Medien" },
  { title: "KI für Blogger & Content Creator", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 12 Lektionen", category: "Kreativ & Medien" },
  { title: "KI für Verlagswesen & Publishing", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 12 Lektionen", category: "Kreativ & Medien" },
  { title: "KI-Automatisierung für Freelancer & Solopreneure", level: "Einsteiger", price: "39,00 €", priceNum: 39, status: "Publiziert", modules: "5 Module · 12 Lektionen", category: "Kreativ & Medien" },
  { title: "Perplexity & KI-Recherche für Profis", level: "Einsteiger", price: "49,00 €", priceNum: 49, status: "Publiziert", modules: "5 Module · 9 Lektionen", category: "Kreativ & Medien" },
];

export const categories = [...new Set(courses.map((c) => c.category))];
